# Generated by Django 5.0.6 on 2024-06-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag_photo', models.ImageField(upload_to='flags/')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=15)),
                ('installed_capacity', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalCumulativeInstalledCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windT.country')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windT.year')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windT.country')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windT.year')),
            ],
        ),
    ]
