# Generated by Django 5.0.6 on 2024-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_description',
            field=models.TextField(default='No description available'),
        ),
    ]
