# Generated by Django 5.0.6 on 2024-06-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windT', '0002_country_country_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='installed_capacity',
        ),
    ]
