# Generated by Django 5.0.6 on 2024-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windT', '0003_remove_country_installed_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthrate',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
