# Generated by Django 5.0.6 on 2024-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windT', '0004_alter_growthrate_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_description',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default='There is no information yet'),
        ),
        migrations.AlterField(
            model_name='country',
            name='land_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='growthrate',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='totalcumulativeinstalledcapacity',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(),
        ),
    ]
