# Generated by Django 5.0.6 on 2024-06-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windT', '0005_remove_country_country_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='description',
            new_name='country_description',
        ),
    ]
